export type Product = {
  id: string;
  name: string;
  slug: string;
  category: string;
  brand: string;
  price: number;
  oldPrice?: number;
  discount?: number;
  specs: string[];
  image: string;
  alt: string;
  rating: number;
  reviews: number;
  stock: number;
  emi?: number;
  isNew?: boolean;
  isFeatured?: boolean;
  badge?: string;
};

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'ASUS ROG Strix G16 Gaming Laptop',
    slug: 'asus-rog-strix-g16',
    category: 'Laptop',
    brand: 'ASUS',
    price: 185000,
    oldPrice: 210000,
    discount: 12,
    specs: ['Intel i9-14900HX', 'RTX 4070', '16GB DDR5', '1TB NVMe'],
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1e06b657f-1778557614857.png',
    alt: 'Black gaming laptop with glowing keyboard on dark surface, dramatic studio lighting',
    rating: 4.8,
    reviews: 124,
    stock: 8,
    emi: 15417,
    isFeatured: true,
    badge: 'Price Drop',
  },
  {
    id: '2',
    name: 'AMD Ryzen 9 7950X Processor',
    slug: 'amd-ryzen-9-7950x',
    category: 'Processor',
    brand: 'AMD',
    price: 68000,
    oldPrice: 75000,
    discount: 9,
    specs: ['16 Cores', '32 Threads', '5.7GHz Boost', 'AM5 Socket'],
    image: 'https://images.unsplash.com/photo-1578416282949-21d754247219',
    alt: 'AMD processor chip on dark background with dramatic lighting highlighting the die',
    rating: 4.9,
    reviews: 89,
    stock: 15,
    emi: 5667,
    isFeatured: true,
  },
  {
    id: '3',
    name: 'NVIDIA GeForce RTX 4090 24GB',
    slug: 'nvidia-rtx-4090',
    category: 'GPU',
    brand: 'NVIDIA',
    price: 195000,
    oldPrice: 220000,
    discount: 11,
    specs: ['24GB GDDR6X', '16384 CUDA Cores', '450W TDP', 'PCIe 4.0'],
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1e3517593-1765198830166.png',
    alt: 'Large graphics card with triple fan cooler against dark background, green accent lighting',
    rating: 4.9,
    reviews: 67,
    stock: 4,
    emi: 16250,
    isFeatured: true,
    badge: 'Low Stock',
  },
  {
    id: '4',
    name: 'Samsung Odyssey G9 49" Curved Monitor',
    slug: 'samsung-odyssey-g9',
    category: 'Monitor',
    brand: 'Samsung',
    price: 125000,
    oldPrice: 140000,
    discount: 11,
    specs: ['49" Ultrawide', '240Hz', '1ms GTG', 'QLED HDR1000'],
    image: 'https://images.unsplash.com/photo-1603481546164-959efb269a4e',
    alt: 'Curved ultrawide monitor displaying colorful gaming scene, dark studio background',
    rating: 4.7,
    reviews: 203,
    stock: 6,
    emi: 10417,
    isFeatured: true,
  },
  {
    id: '5',
    name: 'Samsung Galaxy S24 Ultra',
    slug: 'samsung-galaxy-s24-ultra',
    category: 'Phone',
    brand: 'Samsung',
    price: 145000,
    oldPrice: 160000,
    discount: 9,
    specs: ['Snapdragon 8 Gen 3', '12GB RAM', '512GB', '200MP Camera'],
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1a178d6f1-1766533921118.png',
    alt: 'Modern flagship smartphone with titanium frame on dark reflective surface',
    rating: 4.8,
    reviews: 312,
    stock: 20,
    emi: 12083,
    isFeatured: true,
    isNew: true,
  },
  {
    id: '6',
    name: 'Corsair Vengeance DDR5 32GB Kit',
    slug: 'corsair-vengeance-ddr5-32gb',
    category: 'RAM',
    brand: 'Corsair',
    price: 18500,
    oldPrice: 22000,
    discount: 16,
    specs: ['32GB (2×16GB)', 'DDR5-6000', 'CL36', 'Intel XMP 3.0'],
    image: 'https://images.unsplash.com/photo-1584976853556-9a8f451eb896',
    alt: 'RAM sticks with white heat spreaders on dark background with dramatic side lighting',
    rating: 4.7,
    reviews: 156,
    stock: 25,
    emi: 1542,
    isFeatured: true,
  },
  {
    id: '7',
    name: 'WD Black SN850X 2TB NVMe SSD',
    slug: 'wd-black-sn850x-2tb',
    category: 'Storage',
    brand: 'Western Digital',
    price: 22000,
    oldPrice: 26500,
    discount: 17,
    specs: ['2TB NVMe', 'PCIe Gen4', '7300MB/s Read', 'PS5 Compatible'],
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1b0db511b-1774812065841.png',
    alt: 'M.2 NVMe SSD drive on dark textured surface with dramatic lighting',
    rating: 4.8,
    reviews: 98,
    stock: 30,
    emi: 1833,
    isFeatured: true,
  },
  {
    id: '8',
    name: 'NZXT H9 Elite Full Tower Case',
    slug: 'nzxt-h9-elite',
    category: 'Case',
    brand: 'NZXT',
    price: 28000,
    oldPrice: 32000,
    discount: 13,
    specs: ['Full Tower', 'Tempered Glass', 'E-ATX Support', '4× 140mm Fans'],
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_13bf0d9a3-1772875325285.png',
    alt: 'Premium black PC case with tempered glass panel, RGB lighting visible inside, dark background',
    rating: 4.9,
    reviews: 77,
    stock: 12,
    emi: 2333,
    isFeatured: true,
  },
];

export const FLASH_SALE_PRODUCTS: Product[] = [
  {
    id: 'f1',
    name: 'Logitech G Pro X Superlight 2',
    slug: 'logitech-gpro-x-superlight-2',
    category: 'Peripheral',
    brand: 'Logitech',
    price: 12500,
    oldPrice: 18000,
    discount: 31,
    specs: ['60g Ultra-light', 'HERO 25K Sensor', 'Wireless', '70hr Battery'],
    image: 'https://images.unsplash.com/photo-1700825238348-f76468dc6e81',
    alt: 'White gaming mouse on dark surface with subtle ambient lighting',
    rating: 4.9,
    reviews: 445,
    stock: 3,
    emi: 1042,
    badge: 'Flash Sale',
  },
  {
    id: 'f2',
    name: 'Sony WH-1000XM5 Headphones',
    slug: 'sony-wh1000xm5',
    category: 'Audio',
    brand: 'Sony',
    price: 32000,
    oldPrice: 45000,
    discount: 29,
    specs: ['ANC', '30hr Battery', 'LDAC Hi-Res', 'Multipoint BT'],
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_15350b1ea-1772901666425.png',
    alt: 'Premium black over-ear headphones on dark surface with clean studio lighting',
    rating: 4.8,
    reviews: 678,
    stock: 7,
    emi: 2667,
    badge: 'Flash Sale',
  },
  {
    id: 'f3',
    name: 'ASUS ProArt PA279CRV 4K Monitor',
    slug: 'asus-proart-pa279crv',
    category: 'Monitor',
    brand: 'ASUS',
    price: 68000,
    oldPrice: 85000,
    discount: 20,
    specs: ['27" 4K IPS', '144Hz', '99% DCI-P3', 'Thunderbolt 4'],
    image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1b845f404-1764669618734.png',
    alt: 'Professional 4K monitor with slim bezels showing vibrant color grading work',
    rating: 4.7,
    reviews: 134,
    stock: 5,
    emi: 5667,
    badge: 'Flash Sale',
  },
  {
    id: 'f4',
    name: 'Corsair K100 RGB Mechanical Keyboard',
    slug: 'corsair-k100-rgb',
    category: 'Peripheral',
    brand: 'Corsair',
    price: 18500,
    oldPrice: 25000,
    discount: 26,
    specs: ['OPX Optical-Mech', 'Per-key RGB', 'iCUE Wheel', 'USB Pass-through'],
    image: 'https://images.unsplash.com/photo-1679533662330-457ca8447e7d',
    alt: 'Full-size mechanical keyboard with RGB lighting on dark desk surface',
    rating: 4.8,
    reviews: 289,
    stock: 9,
    emi: 1542,
    badge: 'Flash Sale',
  },
  {
    id: 'f5',
    name: 'Seagate IronWolf Pro 16TB NAS HDD',
    slug: 'seagate-ironwolf-pro-16tb',
    category: 'Storage',
    brand: 'Seagate',
    price: 28000,
    oldPrice: 36000,
    discount: 22,
    specs: ['16TB', '7200 RPM', '256MB Cache', 'CMR Technology'],
    image: 'https://images.unsplash.com/photo-1701721432219-b73c51b595b5',
    alt: 'Hard drive with silver metallic casing on dark background with dramatic product lighting',
    rating: 4.6,
    reviews: 91,
    stock: 14,
    emi: 2333,
    badge: 'Flash Sale',
  },
];

export const CATEGORIES = [
  { id: 'laptop', name: 'Laptop', icon: 'LaptopIcon', slug: 'laptop' },
  { id: 'desktop', name: 'Desktop', icon: 'MonitorIcon', slug: 'desktop' },
  { id: 'gpu', name: 'GPU', icon: 'CpuIcon', slug: 'gpu' },
  { id: 'monitor', name: 'Monitor', icon: 'TvIcon', slug: 'monitor' },
  { id: 'phone', name: 'Phone', icon: 'SmartphoneIcon', slug: 'phone' },
  { id: 'gadget', name: 'Gadget', icon: 'ZapIcon', slug: 'gadget' },
  { id: 'networking', name: 'Networking', icon: 'WifiIcon', slug: 'networking' },
  { id: 'storage', name: 'Storage', icon: 'HardDriveIcon', slug: 'storage' },
  { id: 'peripheral', name: 'Peripheral', icon: 'KeyboardIcon', slug: 'peripheral' },
  { id: 'appliance', name: 'Appliance', icon: 'HomeIcon', slug: 'appliance' },
];

export const PC_BUILDER_COMPONENTS = {
  cpu: [
    {
      id: 'cpu1',
      name: 'AMD Ryzen 9 7950X',
      price: 68000,
      specs: { socket: 'AM5', tdp: 170, ramType: 'DDR5' },
      brand: 'AMD',
      image: 'https://images.unsplash.com/photo-1670751782084-dffc982dc63b',
      alt: 'AMD processor',
    },
    {
      id: 'cpu2',
      name: 'Intel Core i9-14900K',
      price: 72000,
      specs: { socket: 'LGA1700', tdp: 253, ramType: 'DDR5' },
      brand: 'Intel',
      image: 'https://images.unsplash.com/photo-1704820463274-bfe0f07b255b',
      alt: 'Intel processor',
    },
    {
      id: 'cpu3',
      name: 'AMD Ryzen 7 7700X',
      price: 38500,
      specs: { socket: 'AM5', tdp: 105, ramType: 'DDR5' },
      brand: 'AMD',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1ef96da7c-1772174254938.png',
      alt: 'AMD Ryzen 7',
    },
  ],

  motherboard: [
    {
      id: 'mb1',
      name: 'ASUS ROG Crosshair X670E',
      price: 65000,
      specs: { socket: 'AM5', formFactor: 'ATX', ramType: 'DDR5', maxClearance: 360 },
      brand: 'ASUS',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_17bf321cc-1772553723361.png',
      alt: 'ASUS ROG motherboard',
    },
    {
      id: 'mb2',
      name: 'MSI MEG Z790 ACE',
      price: 58000,
      specs: { socket: 'LGA1700', formFactor: 'ATX', ramType: 'DDR5', maxClearance: 340 },
      brand: 'MSI',
      image: 'https://images.unsplash.com/photo-1628600971695-76b2b30c6668',
      alt: 'MSI MEG motherboard',
    },
  ],

  ram: [
    {
      id: 'ram1',
      name: 'Corsair Vengeance DDR5 32GB',
      price: 18500,
      specs: { ramType: 'DDR5', capacity: 32, speed: 6000 },
      brand: 'Corsair',
      image: 'https://images.unsplash.com/photo-1562976540-6aef56e55013',
      alt: 'Corsair RAM',
    },
    {
      id: 'ram2',
      name: 'G.Skill Trident Z5 64GB',
      price: 32000,
      specs: { ramType: 'DDR5', capacity: 64, speed: 6400 },
      brand: 'G.Skill',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1ccbfa5f5-1765378682604.png',
      alt: 'G.Skill RAM',
    },
  ],

  gpu: [
    {
      id: 'gpu1',
      name: 'NVIDIA RTX 4090 24GB',
      price: 195000,
      specs: { tdp: 450, length: 336 },
      brand: 'NVIDIA',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_184602c4d-1772079187447.png',
      alt: 'RTX 4090',
    },
    {
      id: 'gpu2',
      name: 'NVIDIA RTX 4070 Ti Super',
      price: 92000,
      specs: { tdp: 285, length: 305 },
      brand: 'NVIDIA',
      image: 'https://images.unsplash.com/photo-1706954867029-3798018ae194',
      alt: 'RTX 4070 Ti',
    },
    {
      id: 'gpu3',
      name: 'AMD Radeon RX 7900 XTX',
      price: 88000,
      specs: { tdp: 355, length: 287 },
      brand: 'AMD',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_10fa93182-1772172700884.png',
      alt: 'AMD RX 7900 XTX',
    },
  ],

  storage: [
    {
      id: 'st1',
      name: 'WD Black SN850X 2TB',
      price: 22000,
      specs: { type: 'NVMe', capacity: 2000 },
      brand: 'WD',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_145853ef8-1765897692492.png',
      alt: 'WD NVMe SSD',
    },
    {
      id: 'st2',
      name: 'Samsung 990 Pro 1TB',
      price: 14500,
      specs: { type: 'NVMe', capacity: 1000 },
      brand: 'Samsung',
      image: 'https://images.unsplash.com/photo-1659543038850-cf8daec7b500',
      alt: 'Samsung SSD',
    },
  ],

  psu: [
    {
      id: 'psu1',
      name: 'Corsair HX1200 Platinum',
      price: 28000,
      specs: { wattage: 1200, rating: '80+ Platinum' },
      brand: 'Corsair',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1f30d5a91-1769890421029.png',
      alt: 'Corsair PSU',
    },
    {
      id: 'psu2',
      name: 'EVGA SuperNOVA 850 G6',
      price: 18500,
      specs: { wattage: 850, rating: '80+ Gold' },
      brand: 'EVGA',
      image: 'https://images.unsplash.com/photo-1674845574169-9269e9b1575c',
      alt: 'EVGA PSU',
    },
  ],

  case: [
    {
      id: 'case1',
      name: 'NZXT H9 Elite',
      price: 28000,
      specs: { formFactor: 'ATX', maxGpuLength: 420 },
      brand: 'NZXT',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1ce5f948b-1781710303391.png',
      alt: 'NZXT case',
    },
    {
      id: 'case2',
      name: 'Lian Li O11 Dynamic EVO',
      price: 22000,
      specs: { formFactor: 'ATX', maxGpuLength: 380 },
      brand: 'Lian Li',
      image: 'https://images.unsplash.com/photo-1729986879703-6f3538b59e20',
      alt: 'Lian Li case',
    },
  ],

  cooler: [
    {
      id: 'cool1',
      name: 'NZXT Kraken Elite 360 RGB',
      price: 22000,
      specs: { type: 'AIO', radiatorSize: 360, tdpSupport: 400 },
      brand: 'NZXT',
      image: 'https://img.rocket.new/generatedImages/rocket_gen_img_1849a1449-1766044402940.png',
      alt: 'NZXT Kraken AIO cooler',
    },
    {
      id: 'cool2',
      name: 'Noctua NH-D15 Chromax',
      price: 12000,
      specs: { type: 'Air', radiatorSize: 0, tdpSupport: 250 },
      brand: 'Noctua',
      image: 'https://images.unsplash.com/photo-1674775046052-87f1246dc570',
      alt: 'Noctua air cooler',
    },
  ],
};

export const CART_ITEMS_MOCK = [
  { ...PRODUCTS[0], qty: 1 },
  { ...PRODUCTS[5], qty: 2 },
];

export const DISTRICTS = [
  'Dhaka',
  'Chittagong',
  'Sylhet',
  'Rajshahi',
  'Khulna',
  'Barisal',
  'Rangpur',
  'Mymensingh',
  'Comilla',
  'Narayanganj',
];

export const formatPrice = (price: number) => `৳${price.toLocaleString('en-BD')}`;

export const formatEmi = (price: number, months = 12) =>
  `৳${Math.ceil(price / months).toLocaleString('en-BD')}/mo × ${months}`;
